// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:26d8a14f-59e0-4af8-8fbe-ac53434c9d99",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_6GGNF2MOt",
    "aws_user_pools_web_client_id": "2un6s78arb5ogfl9s4ghrdomt9"
};


export default awsmobile;
